// Sampling grid: 100 m lattice of points per fire, aligned to the Ordnance
// Survey National Grid, generated by tools/build_sampling_grid.py.
//
// A point's identity IS its OS coordinates - "E312350 N914250" - so it is
// stable across rebuilds, meaningful on any UK paper map, and two volunteers
// at the same node record against the same ID.

import * as DB from './db.js';

/** Cache key for a fire's grid blob inside the pack storage. */
export const gridKey = (fireId) => `grid/${fireId}`;

const cache = new Map();       // fireId -> { spacing, points } | null
const MAX_CACHED = 8;          // grids are up to ~300 kB parsed; keep a few

/**
 * Load one fire's grid: packed copy first (works offline), network second.
 * Resolves null when the fire has no grid file at all.
 */
export async function loadGrid(fireId) {
  if (cache.has(fireId)) return cache.get(fireId);

  let data = null;
  try {
    const blob = await DB.getTile(gridKey(fireId));
    if (blob) data = JSON.parse(await blob.text());
  } catch { /* fall through to network */ }

  if (!data) {
    try {
      const r = await fetch(`data/grid/${encodeURIComponent(fireId)}.json`);
      if (r.ok) data = await r.json();
    } catch { /* offline and not packed */ }
  }

  if (cache.size >= MAX_CACHED) cache.delete(cache.keys().next().value);
  cache.set(fireId, data);
  return data;
}

/** "E312350 N914250" - the human/CSV form of a node. */
export const nodeId = (e, n) => `E${e} N${n}`;

/**
 * Nearest grid node of one fire to a position.
 * Returns { e, n, lat, lon, id, distM } or null.
 */
export async function nearestNode(fireId, lat, lon) {
  const g = await loadGrid(fireId);
  if (!g || !g.points || !g.points.length) return null;

  // Equirectangular is plenty at <10 km scales, and 80x cheaper than
  // haversine over ten thousand candidates.
  const mLat = 111320;
  const mLon = 111320 * Math.cos((lat * Math.PI) / 180);
  let best = null, bestD2 = Infinity;
  for (const [e, n, plat, plon] of g.points) {
    const dy = (plat - lat) * mLat;
    const dx = (plon - lon) * mLon;
    const d2 = dx * dx + dy * dy;
    if (d2 < bestD2) { bestD2 = d2; best = [e, n, plat, plon]; }
  }
  const [e, n, plat, plon] = best;
  return { e, n, lat: plat, lon: plon, id: nodeId(e, n), distM: Math.sqrt(bestD2) };
}

/** Distance + compass direction from a position to a node, for navigation. */
export function towards(fromLat, fromLon, toLat, toLon) {
  const mLat = 111320;
  const mLon = 111320 * Math.cos((fromLat * Math.PI) / 180);
  const dy = (toLat - fromLat) * mLat;
  const dx = (toLon - fromLon) * mLon;
  const dist = Math.hypot(dx, dy);
  const deg = ((Math.atan2(dx, dy) * 180) / Math.PI + 360) % 360;
  const compass = ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'][Math.round(deg / 45) % 8];
  return { distM: dist, bearingDeg: Math.round(deg), compass };
}
